### ISSUE TITLE
Apply filters to Search Bar to allow dynamic population of some fields 

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1320] opened 2019-06-03 21:38 UTC
TBD

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1125634550311937)

**Comment by soulseekah** [comment] 2019-10-19 18:32
Duplicate of https://github.com/gravityview/GravityView/issues/820

**Closed by soulseekah** 2019-10-19 18:32 UTC
Labels: Enhancement
