### ISSUE TITLE
Sort on Table View is not working

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1323] opened 2019-06-12 01:41 UTC
Sometimes it doesn't work when there's a search bar (reported by a user) and sometimes it simply doesn't sort at all (on my test website).

GV 2.3.2

**Comment by rafaehlers** [comment] 2019-06-12 01:41
https://secure.helpscout.net/conversation/875973599/21087?folderId=408730

**Comment by jaspekang** [comment] 2019-06-13 22:00
same issue here.

**Comment by zackkatz** [comment] 2019-06-20 18:11
@rafaehlers Can you provide steps to reproduce?

**Comment by rafaehlers** [comment] 2019-07-04 06:52
@zackkatz here's another example on a Table View where sort is not working at all: https://secure.helpscout.net/conversation/894930635/21401/

**Comment by zackkatz** [comment] 2019-08-01 21:13
@soulseekah This issue is caused by this code:

https://github.com/gravityview/GravityView/blob/master/future/includes/class-gv-view.php#L982-L985

When accessing this View URL:
`https://example.com/view/vib-listing/?sort[20]=asc`

These sorts never get applied: 

```
array (size=2)
  'sort_field_ids' => 
    array (size=1)
      0 => int 20
  'sort_directions' => 
    array (size=1)
      0 => string 'asc' (length=3)
```

**Comment by zackkatz** [comment] 2019-08-01 21:16
And tests are still green when commenting that section out…

**Comment by zackkatz** [comment] 2019-08-01 22:21
@jaspekang The issue should be fixed with this: https://share.gravityview.co/34t0ig - please test.

**Comment by rafaehlers** [comment] 2019-08-09 23:41
@zackkatz that fixed it on https://secure.helpscout.net/conversation/923653886/21924

**Comment by jaspekang** [comment] 2019-08-13 01:27
> @jaspekang The issue should be fixed with this: https://share.gravityview.co/34t0ig - please test.

Thanks @zackkatz 
It's working perfectly.

**Comment by rafaehlers** [comment] 2019-08-20 23:40
That didn't work here: https://secure.helpscout.net/conversation/879485389/21157

**Comment by soulseekah** [comment] 2019-09-17 14:37
> That didn't work here: https://secure.helpscout.net/conversation/879485389/21157

I've checked this several times and also looked through the client site in HS#21157, the arrows seem to work fine right now.

Please confirm and reopen if needed.

**Comment by soulseekah** [comment] 2019-09-18 03:59
There's a shortcode sort_field override in the last case.

`[gravityview id='3834' sort_field="4"]`

**Comment by Raul1231** [comment] 2019-09-25 00:10
I have the same problem, I can´t sort the result properly

![image](https://user-images.githubusercontent.com/49456398/65559057-614bd380-df39-11e9-983a-991a3841ff45.png)

In the photo, 15 is less than 2, is like only see the first number.

Have someone the same problem? how do you resolve it?

**Comment by soulseekah** [comment] 2019-09-29 13:08
Looks like Numeric is misbehavin, you need to make sure `is_numeric` is being set for your field. Is it a Number field? Or a text field? Try converting to a Number field.

Please contact support@gravityview.com for further assistance.

**Comment by soulseekah** [comment] 2019-10-03 15:06
I'd say this can be closed again. Until better days.

**Closed** 2019-10-07 23:03 UTC
Labels: Bug, Priority: High
