### ISSUE TITLE
[Survey Add-On] no way to pull scoring of Likert choices

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1369] opened 2019-11-06 03:42 UTC
![image](https://user-images.githubusercontent.com/1222472/68266525-1b9d2300-002e-11ea-8174-e7349db68317.png)

I tried using the field Merge Tag in conjunction with the :value modifier `{Survey:1:value}` but that didnt' work.

Tested on GV 2.4.1.1

**Comment by rafaehlers** [comment] 2019-11-06 03:42
https://secure.helpscout.net/conversation/998114679/23231

**Comment by soulseekah** [comment] 2019-11-06 07:38
We implemented this quite a bit of time ago.

**Comment by soulseekah** [comment] 2019-11-06 07:38
https://github.com/gravityview/GravityView/issues/1195

Needs testing. Closing as duplicate of #1195

**Closed by soulseekah** 2019-11-06 07:38 UTC
Labels: Enhancement
