### ISSUE TITLE
Implement an auto-save feature to prevent a View from losing its settings

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#791] opened 2016-11-07 17:33 UTC
To prevent our users from losing all their settings when creating a new View, we must save the meta values.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995650704611315)

**Comment by zackkatz** [comment] 2022-05-19 16:35
This is a duplicate of #1655

**Closed by zackkatz** 2022-05-19 16:35 UTC
Labels: Enhancement, Core: Administration, Difficulty: Medium, Priority: Low
