### ISSUE TITLE
"What should be displayed" only showing in Checkbox fields

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#717] opened 2016-06-16 03:58 UTC
Should show in "Checkbox", "Radio", "Drop Down" field options.

![image](https://user-images.githubusercontent.com/1222472/135925371-10c0cb95-abf9-4643-abfc-d19b6ec9a91c.png)

As of GF 2.13.1 that's still missing.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995646276536273)

**Comment by rafaehlers** [comment] 2021-10-04 22:49
Duplicate of: https://github.com/gravityview/GravityView/issues/961

**Closed by rafaehlers** 2021-10-04 22:49 UTC
Labels: Bug, Core: Administration, Difficulty: Low
