### ISSUE TITLE
The {get} Merge Tag doesn't work on a DataTables View called by the [gravityview] shortcode

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1371] opened 2019-11-07 01:19 UTC
Usage:

`[gravityview id="12" search_field="created_by" search_value="{get:userid}"]`

Tested on 
GV 2.4.1.1 
DT 2.4.1

**Comment by rafaehlers** [comment] 2019-11-07 01:20
https://secure.helpscout.net/conversation/991844427/23130

**Comment by soulseekah** [comment] 2019-11-07 20:07
Works well on `develop`:

![image](https://user-images.githubusercontent.com/685880/68423451-3351e400-01b3-11ea-820b-e8eae97b8138.png)

![image](https://user-images.githubusercontent.com/685880/68423469-3a78f200-01b3-11ea-861d-82cc3938e83a.png)

Might be a user error. Test and ask for more access, probably has some sort of filter kicking off somewhere, @rafaehlers, please and thank you.

**Comment by zackkatz** [comment] 2019-11-07 20:09
@soulseekah The issue is on DataTables, not Core.

**Comment by soulseekah** [comment] 2019-11-07 20:10
Duh!

**Comment by soulseekah** [comment] 2019-11-09 12:35
This is a pretty difficult issue to resolve.

The main problem is that the AJAX data call has absolutely no context of the filters that were passed to the shortcode and grabs the View as configured statically in the backend.

I've tried a couple of approaches, nothing too successful so far, but I think this can be had.

**Comment by soulseekah** [comment] 2019-11-09 13:03
Can we have a test on `develop`  for both GravityView and Datatables, please? @rafaehlers @jlgrisham

**Comment by zackkatz** [comment] 2019-12-13 00:17
@soulseekah When we need testing, please make sure to add to the Development Planning project and assign to the Needs Testing column:

![](https://i.gravityview.co/3pSlD1+)

**Closed** 2019-12-13 00:19 UTC
Labels: Bug, Difficulty: High
