### ISSUE TITLE
JS Error - "GForm is not defined" when using date search fields

### ISSUE THREAD

**Issue by Idealien** [gravityview/GravityView#544] opened 2015-10-07 13:56 UTC
"ReferenceError: gform is not defined
optionsObj = gform.applyFilters('gform_datepicker_options_pre_init', optionsObj,..."

The file /wp-content/plugins/gravityforms/js/datepicker.js?ver=1.3.9 is loaded successfully

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995626339219184)

**Comment by zackkatz** [comment] 2015-10-10 18:46
@Idealien Thanks for reporting!

**Comment by zackkatz** [comment] 2016-05-12 21:04
@rafaehlers I've not been able to reproduce, have you?

**Comment by zackkatz** [comment] 2019-10-13 19:03
Closing due to how old this is.

**Closed by zackkatz** 2019-10-13 19:03 UTC
Labels: Core: Search Bar

**Comment by SuchiMehta26** [comment] 2022-09-01 06:31
I m facing the same issue , anyone pls tell me how to solve this

**Comment by rafaehlers** [comment] 2022-09-01 21:10
@SuchiMehta26 please contact our support so we can check this for you: https://www.gravitykit.com/support/
