### ISSUE TITLE
Drop Down field value empty in Custom Content field in multiple entries context unless matching search is performed

### ISSUE THREAD

**Issue by zackkatz** [gravityview/GravityView#859] opened 2017-03-07 17:19 UTC
When a Merge Tag is used in Custom Content field, the value is empty. When the Drop Down field is displayed, the value displays properly.

Except the Merge Tag in the Custom Content field starts working (and the `$entry` value exists) when there's a search performed:

`example.com/view/see-what-i-mean/` - The drop down merge tag value is empty
`example.com/view/see-what-i-mean/?gv_search=matches` - The drop down entry value is filled

It's not a Merge Tag issue; `$entry` is missing the value at the field ID, `$value` and `$display_value` are empty. It's just gone.

I haven't been able to reproduce.

https://secure.helpscout.net/conversation/328876351/8465/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995653678243143)

**Comment by soulseekah** [comment] 2019-10-14 17:00
I propose a close on this due to inactivity.

**Comment by zackkatz** [comment] 2019-10-14 19:49
@jlgrisham Can you please test?

**Comment by rafaehlers** [comment] 2021-10-04 22:26
I'm closing this as the issue description doesn't give clear steps on how to reproduce that and we haven't had any similar reports recently.

**Closed by rafaehlers** 2021-10-04 22:26 UTC
Labels: Bug, Works for Me, Difficulty: High, Core: API, Priority: Low, Status: Needs Testing
