### ISSUE TITLE
[gv_math] is not working inside [gvlogic]

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1286] opened 2019-03-19 23:40 UTC
What is described here: https://docs.gravityview.co/article/431-can-i-use-gvmath-with-gvlogic doesn't work anymore on `GV 2.2.5` ver and `Math ver 1.1.1`

![image](https://user-images.githubusercontent.com/1222472/54648976-0ff0f200-4a87-11e9-8db1-58d68f245cb9.png)

## Contents of Custom Content field
```
[gvlogic if="{Calculate:1:value}" is="Yes"]
[gv_math]1+1[/gv_math]
[/gvlogic]
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1115096396557463)

**Comment by rafaehlers** [comment] 2019-03-19 23:41
https://secure.helpscout.net/conversation/804054990/19701/

**Comment by soulseekah** [comment] 2019-08-26 12:56
The merge tag doesn't appear to be working at all and I can't find a version where it does. Could be a GF issue.

**Comment by soulseekah** [comment] 2019-08-27 08:00
Found out the reason. Unrelated.

Reproduced:

![image](https://user-images.githubusercontent.com/685880/63752432-e64fb880-c8b9-11e9-899f-dda2d4371aeb.png)

**Comment by soulseekah** [comment] 2019-08-27 11:27
I've seen this before here https://github.com/gravityview/Math/issues/29

**Comment by soulseekah** [comment] 2019-08-27 11:44
So the quick fix might be to do something like this:

```php
add_filter( 'gravityview/merge_tags/do_replace_variables', function( $r ) {
	if ( class_exists( 'GravityView_Math_Shortcode' ) && ! is_null( GravityView_Math_Shortcode::$instance ) ) {
		remove_filter( 'gravityview/merge_tags/do_replace_variables', array( GravityView_Math_Shortcode::$instance, 'dont_strip_gv_shortcodes' ), 2, 11 );
	}
	return $r;
} );
```

This is definitely a Math issue. I'm going to close this, refer to the corresponding Math issue linked in my previous response.

**Closed by soulseekah** 2019-08-27 11:44 UTC
Labels: Bug, Core: Shortcodes
