### ISSUE TITLE
Move Featured Entries to the Top is breaking the Search (again)

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1308] opened 2019-04-30 19:04 UTC
TBD
GV 2.3.1 and FE 2.0.3

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/1120648228242242)

**Comment by rafaehlers** [comment] 2019-04-30 19:04
https://secure.helpscout.net/conversation/837418733/20397/

**Comment by soulseekah** [comment] 2019-09-18 06:28
This has probably been fixed in https://github.com/gravityview/Featured-Entries/pull/27

Please confirm and close.

**Comment by zackkatz** [comment] 2019-09-19 18:05
@rafaehlers Can you please test?

**Comment by zackkatz** [comment] 2019-10-07 23:03
@rafaehlers @jlgrisham Please test.

**Comment by rafaehlers** [comment] 2019-10-08 04:45
Sorry, I forgot to mention this was tested and fixed already.

**Comment by bennemann** [comment] 2020-04-01 00:03
It seems "Move Featured Entries to the Top" is still breaking the search.

If "Move Featured Entries to Top" is checked on the settings of a View, you can't combine an Advanced Filter condition and a Search Bar filter. You can have them separately, but not combined.

Steps to reproduce: 
1) Have "Move Featured Entries to the Top" checked on a View.
2) Add a Search Bar (any) and an Advanced Filter condition (any).
3) Try to search.

You'll get an SQL error about an unknown column. In fact, the problem is that it tries to access the column using an unset alias.

Here's an example:
WordPress database error: [Unknown column 'm3.meta_value' in 'where clause']
SELECT SQL_CALC_FOUND_ROWS DISTINCT `t1`.`id` FROM `wp_gf_entry` AS `t1` LEFT JOIN `wp_gf_entry_meta` AS `m2` ON (`m2`.`entry_id` = `t1`.`id` AND `m2`.`meta_key` = 2) WHERE (`t1`.`form_id` IN (9) AND ((`t1`.`status` = 'active' AND (`m2`.`meta_key` = 2 AND `m2`.`meta_value` = 'test')) AND `m3`.`meta_value` LIKE '%test%')) ORDER BY `t1`.`is_starred` DESC, `t1`.`id` DESC LIMIT 25

GV 2.7.1 and FE 2.0.5

**Comment by soulseekah** [comment] 2020-04-21 09:47
> 2. Add a Search Bar (any) and an Advanced Filter condition (any).

This actually works fine. Having an Any/Everything restriction has the correct SQL generated.

In the example error the Advanced Filter was set to field ID 2. So the correct way to reproduce it is to set explicit fields for either the Search Bar or the AF (or both).

**Comment by soulseekah** [comment] 2020-04-21 10:53
Fixed by creating a stripping utility method and utilizing it inside the Featured Entries plugin. Please test and let me know.

This may need some unit tests.

Cheers.

**Comment by rafaehlers** [comment] 2020-08-04 22:53
@soulseekah not working here: https://secure.helpscout.net/conversation/1221497152/27985/

**Comment by rafaehlers** [comment] 2020-08-26 21:19
https://secure.helpscout.net/conversation/1257628778/28701/

**Comment by mrcasual** [comment] 2020-09-08 18:09
@soulseekah https://github.com/gravityview/GravityView/commit/f5e79faaab4609ca1de115d5f60616eb129a5dad and https://github.com/gravityview/Featured-Entries/commit/9e9b5e62f8e584b8aefd9d45a021a788ff7b6f6a break the search when a filter condition contains a multi-input field.

![](https://i.imgur.com/qs28jmZ.png)
![](https://i.imgur.com/JQ5NuIx.png)

...`meta_key` should have a `LIKE` operator. Could you please look into this?

**Comment by rafaehlers** [comment] 2020-10-14 01:54
https://secure.helpscout.net/conversation/1307804000/29710/

**Comment by bennemann** [comment] 2021-04-26 13:27
https://secure.helpscout.net/conversation/1483767408/33817/

**Comment by mrcasual** [comment] 2021-04-29 18:56
Fixed by https://github.com/gravityview/Featured-Entries/releases/tag/v2.0.7

Time to close this sucker :) 🎆

**Closed by mrcasual** 2021-04-29 18:56 UTC
Labels: Bug, Priority: High
