### ISSUE TITLE
Field value being erased on edit entry page when conditional logic is not met

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#840] opened 2017-02-08 02:37 UTC
Basically, if you add a field to the Edit Entry page to be editable, but the parent field on which this field relies on is not present (because of a conditional logic rule), this field won’t show up (that's okay). But if you modify any other field value and update the entry, that field which haven't showed up will get its value erased.

You can test it here: http://gravityview.com.br/view/conditional-logic-simple/

![download](https://cloud.githubusercontent.com/assets/1222472/22721251/d02d3ae2-edaf-11e6-95c4-2925285e93ef.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995653027489409)

**Comment by rafaehlers** [comment] 2017-02-08 02:38
https://secure.helpscout.net/conversation/315583016/8142/?folderId=408735

**Comment by zackkatz** [comment] 2017-03-29 06:25
@rafaehlers Is this still open?

**Comment by rafaehlers** [comment] 2017-03-29 13:39
@zackkatz the View linked to replicate was changed already. Is that what you asked?

**Comment by soulseekah** [comment] 2019-02-06 19:57
This is still an issue. I reproduced and working on it.

**Comment by soulseekah** [comment] 2019-02-12 11:32
Fixed in https://github.com/gravityview/GravityView/commit/0a01c532ef1fc3b106096a26501c63f2ca3209c5 with a unit test, but we do need some manual testing as our edit coverage is pretty scarce at the moment.

@rafaehlers please spend some time playing with it before we release.

**Comment by soulseekah** [comment] 2019-04-16 10:06
> @rafaehlers please spend some time playing with it before we release.

lol, it doesn't work, sorry guys; working on a fix

**Comment by rafaehlers** [comment] 2019-05-07 16:09
Fixed on develop branch 👍

**Comment by rafaehlers** [comment] 2019-06-25 03:50
The new code introduced on the latest version by @soulseekah doesn't expect field IDs which are noninteger on conditional logic rules on line 1961 of this file: `/gravityview/includes/extensions/edit-entry/class-edit-entry-render.php`

`​$value = GFAPI::get_field( $the_form, $rule['fieldId'] )->get_value_export( $this->entry );`

`$rule['fieldId']` can sometimes be:

```
Array
(
    [fieldId] => __adv_cond_logic
    [operator] => is
    [value] => field/128/20
)
```

```
[conditionalLogic] => Array
        (
            [actionType] => show
            [logicType] => all
            [rules] => Array
                (
                    [0] => Array
                        (
                            [fieldId] => 1
                            [operator] => is
                            [value] => 1561420800
                        )

                    [1] => Array
                        (
                            [fieldId] => _gpcld_current_time
                            [operator] => <
                            [value] => 11:00am
                        )

                )

        )
```

That generates a Fatal Error: 
```
PHP Fatal error:  Uncaught Error: Call to a member function get_value_export() on boolean in C:\wamp64\www\TestDev\wp-content\plugins\gravityview\includes\extensions\edit-entry\class-edit-entry-render.php:1961
Stack trace:
#0 C:\wamp64\www\TestDev\wp-content\plugins\gravityview\includes\extensions\edit-entry\class-edit-entry-render.php(1160): GravityView_Edit_Entry_Render->filter_conditional_logic(Array)
#1 C:\wamp64\www\TestDev\wp-includes\class-wp-hook.php(288): GravityView_Edit_Entry_Render->filter_modify_form_fields(Array, false, Array)
#2 C:\wamp64\www\TestDev\wp-includes\plugin.php(208): WP_Hook->apply_filters(Array, Array)
#3 C:\wamp64\www\TestDev\wp-content\plugins\gravityforms\gravityforms.php(5776): apply_filters('gform_pre_rende...', Array, false, Array, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
#4 C:\wamp64\www\TestDev\wp-content\plugins\gravityforms\form_display.php(833): gf_apply_filters('gform_pre_rende...', Array, false, Array)
#5 C:\wamp64\www\TestDev\wp-content\plugins\gravityview\includes\extensions\ed in C:\wamp64\www\TestDev\wp-content\plugins\gravityview\includes\extensions\edit-entry\class-edit-entry-render.php on line 1961
```

That can be fixed by replacing that line with this code:
`$value = GFAPI::get_field( $the_form, $field['id'] )->get_value_export( $this->entry );`

which will grab the field ID (required by the `get_field` function) from the `$field` array instead of getting it from the `$rule` array which can have a non-integer ID.

That fixed it on these two websites:
https://secure.helpscout.net/conversation/872550966/21031/
https://secure.helpscout.net/conversation/885630858/21259

**Comment by soulseekah** [comment] 2019-06-25 11:22
I don't think it's a good solution and may get logical issues to pop up.

`$field['id']` is not equal to `$rule['fieldId']` they're different things, so your comparison value will end up being different. I was trying to write some tests and couldn't get the old ones to pass because you're starting to compare different fields all of a sudden.

I suggest you revert the fix as the condition values checked are for the field that is being hidden not for the field that actually needs to be checked.

I'm pretty sure that we just need to add `get_meta` if it's non-numeric and not an entry property (column).

**Comment by soulseekah** [comment] 2019-06-26 15:00
Pushed a fix. Can you please test on the target websites? Only that file was changed you can grab it from here: https://raw.githubusercontent.com/gravityview/GravityView/0cccc6bb9e65eb978d76181f5b460f352cf0fbcd/includes/extensions/edit-entry/class-edit-entry-render.php

**Comment by rafaehlers** [comment] 2019-06-27 00:15
@soulseekah that fixes it. @zackkatz let's release whenever.

**Comment by soulseekah** [comment] 2019-10-28 11:41
https://secure.helpscout.net/conversation/989935174/23107/

Managed to reproduce something similar. Reopening.

**Comment by soulseekah** [comment] 2019-10-30 10:45
Our test does not fail because a call to `GFFormsModel::get_field` has an internal cache in it that is called on regular requests and contains ALL the fields from the form.

Inside our edit entry test the cache is empty and the edit form has only got one field in it. The rest are hidden.

I think I now know how to make the test fail.

**Comment by soulseekah** [comment] 2019-10-30 19:25
![image](https://user-images.githubusercontent.com/685880/67891702-29e9cb80-fb64-11e9-8ae2-46aa13d9a2e8.png)

Something like this is the quickest fix, but I suspect there will be logical problems elsewhere.

**Comment by soulseekah** [comment] 2019-11-01 14:01
Closing until more edge cases pop up.

**Comment by soulseekah** [comment] 2019-11-05 11:44
https://secure.helpscout.net/conversation/995980900/23204

**Closed** 2019-11-05 12:20 UTC
Labels: Bug, Core: Edit Entry, Priority: High, Reproducible
