### ISSUE TITLE
Value of Conditional field is deleted when its visibility is toggled 

### ISSUE THREAD

**Issue by altoin** [gravityview/GravityView#1295] opened 2019-04-03 17:59 UTC
The value of a conditional field is deleted when you toggle its visibility.

https://debug.gravityview.co/testing/view/conditional-entry/

If you change Do you want to open an account? to know and update the View, The content in the address field will be removed completely.

**Comment by soulseekah** [comment] 2019-09-23 06:22
I want to close this off as intentional, @zackkatz 

If the condition is not met the value should not be present, as if it was never entered.

Please discuss.

**Comment by rafaehlers** [comment] 2021-10-05 20:56
This is intended behavior. We have a filter otherwise:
`add_filter( 'gravityview/edit_entry/unset_hidden_field_values', '__return_false');`

**Closed by rafaehlers** 2021-10-05 20:56 UTC
