### ISSUE TITLE
Edit/Delete Entry Links Don't Work When Shortcode Filter Applied

### ISSUE THREAD

**Issue by dhughes55** [gravityview/GravityView#1755] opened 2022-09-27 14:06 UTC
When I add a shortcode to load my view, the edit/delete entry links work as expected:
![image](https://user-images.githubusercontent.com/38288735/192546299-56f14c34-420b-4c9f-85d2-643dbaa0838f.png)
![image](https://user-images.githubusercontent.com/38288735/192548258-79308d92-7afb-457a-abef-4a9e30d2734f.png)

But when I add a filter to the shortcode, the edit/entry links disappear even though editing/deleting entries is still enabled:
![image](https://user-images.githubusercontent.com/38288735/192548363-6e3cafdb-cdc2-492c-850d-de3ec5f4ecc7.png)
![image](https://user-images.githubusercontent.com/38288735/192548435-b9924167-be7b-4173-a1ae-02e3e8a08f6a.png)

This problem occurs in both the multiple entries layout and the single entry layout.

**Comment by rafaehlers** [comment] 2022-09-27 18:21
Duplicate of https://github.com/gravityview/GravityView/issues/1537

**Closed by rafaehlers** 2022-09-27 18:21 UTC
